language: node_js
node_js:
- 12
script:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: Xf9nUi4TRLY6cvfJghP92PmwCUN+bY9IEElJS0yqYcZq85jindr+k3leOlqKM5iartEgMLN+M+lsSZ7sQ+BbmUcwRLLBwwEJ6jqQeOstzpcZd+KzgguZcM8XGGhq0TXM1bEUU2vKMcmDdA5Sh7Cgk2wld6O96JIJ5EDipdn9BHJ6BAHo2uHPVaGmY7bYBSiaO1kGvMbVJW0XmdmrlI3AQmuK6uaGyal28pNyhRsuJyHcHvaNfnu2RoRIHEDiYGRvGu0glu/Xkgyj7a5iFL3t7xCkuZMSovueylGCmJzxQOFFdHwGdReJ6+LcN2hG0u3ByidfGcvjn5DVoW08H8CC+v0FSWD13znF7FxIc8T439xRE29tIiJArYlRG+O+OBgpk36lcrDPLRxirdrDGpiqVmYoKd0lesI9GzFHkhqka6NA96y7YMiF0sVWJngrH7nnnbONU63RNo95m6UQmV0c64jgKXlqf7tL7V39nDJ33C9iMPWXEq0aEXTYGWIxW/MmogmfM0NNy7qMUsoLqH/zQ4bMwZvLJYR9lzH5GiWFDYz+Ygnh+K9tlNsjnAYaYfM4W/m2+viTQ9S6X+BYROPyYJjLQIGN7AzcOses+jJn+5I43EESq+FYfUvo4sdEKHjOqMjhhf5BZG1/978GV7iA8QFU2rvXo2fkR31dvv5AWtY=
  app: mensaje-app
  on:
    repo: oluwaferanmiadetunji/messaging-application-backend
    branch: master
  skip_cleanup: 'true'
